<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UsingDataControls.aspx.cs" Inherits="ProductTest.UsingDataControls" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Using data controls</title>
    <style type="text/css">
        .menu td{padding:5px 0px;}
        .selectedPage a{font-weight:bold;color:red;}
    </style>

</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:DropDownList AutoPostBack="true" ID="ddlCompany" runat="server" 
            onselectedindexchanged="ddlCompany_SelectedIndexChanged">
        </asp:DropDownList>
        <br />
        <asp:Label runat="server" ID="lblCompany"></asp:Label>
        <hr />
        <asp:RadioButtonList ID="RadioButtonList1" runat="server">
        </asp:RadioButtonList>
        <asp:LinkButton ID="lkbtnVote" runat="server" onclick="lkbtnVote_Click">Bình chọn</asp:LinkButton>
    </div>
    <asp:Label runat="server" ID="lblResultRadioBtn"></asp:Label>
    <hr />
    Điều khiển ListBox<br />
    <asp:ListBox AutoPostBack="true" ID="ListBox1" runat="server" 
        SelectionMode="Multiple"></asp:ListBox><br />
    <br />
    <asp:Button ID="btnSelectListBox" runat="server" Text="Chọn" 
        onclick="btnSelectListBox_Click" />
    <br />
    Bạn đã chọn:<br />
    <asp:Label ID="lblSelectListBox" runat="server"></asp:Label>
    <hr />
    <asp:CheckBoxList AutoPostBack="true" ID="CheckBoxList1" runat="server">
    </asp:CheckBoxList>
    <asp:Button ID="btnChon" runat="server" Text="Chọn" onclick="btnChon_Click" />
    <br />
    Bạn đã chọn:<br />
    <asp:Label ID="lblSelectedCheckBoxList" runat="server"></asp:Label>
    
    <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1" 
        AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" 
        DataKeyNames="pkUserID" PageSize="4" Width="691px" 
        onselectedindexchanged="GridView1_SelectedIndexChanged" 
        OnDataBound="GridView1_DataBound" BackColor="#DEBA84" BorderColor="#DEBA84" 
        BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2"
        AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True">
        <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
        <Columns>
            <asp:BoundField DataField="pkUserID" HeaderText="User ID" ReadOnly="True" SortExpression="pkUserID"></asp:BoundField>
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
            <asp:CheckBoxField DataField="Sex" HeaderText="Sex" SortExpression="Sex" />
            <asp:CheckBoxField DataField="Working" HeaderText="Working" 
                SortExpression="Working" />
        </Columns>
        <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
        <PagerTemplate>
            <table align="center">
                <tr>
                    <td>
                        <asp:LinkButton ID="lnkPrevious" runat="server" Text="<<" 
                            CommandName="Page" CommandArgument="Prev" ToolTip="Previous Page"></asp:LinkButton>
                    </td>
                    <td>
                           <asp:Menu ID="menuPager" StaticSelectedStyle-CssClass="selectedPage" 
                            runat="server" OnMenuItemClick="menuPager_MenuItemClick" 
                                    BackColor="#FFFBD6" DynamicHorizontalOffset="2" Font-Names="Verdana" 
                                    Font-Size="0.8em" ForeColor="#990000" StaticSubMenuIndent="10px" Orientation="Horizontal">
                                    <StaticSelectedStyle CssClass="selectedPage" BackColor="#FFCC66"></StaticSelectedStyle>
                                    <StaticMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
                                    <DynamicHoverStyle BackColor="#990000" ForeColor="White" />
                                    <DynamicMenuStyle BackColor="#FFFBD6" />
                                    <DynamicSelectedStyle BackColor="#FFCC66" />
                                    <DynamicMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
                                    <StaticHoverStyle BackColor="#990000" ForeColor="White" />
                            </asp:Menu>
                    </td>
                    <td>
                        <asp:LinkButton id="lnkNext" Text=">>" 
                            CommandName="Page" CommandArgument="Next" ToolTip="Next Page" Runat="server"></asp:LinkButton>
                    </td>
                </tr>
            </table>
        </PagerTemplate>
        <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        DeleteCommand="DELETE FROM [tblUser] WHERE [pkUserID] = @pkUserID" 
        InsertCommand="INSERT INTO [tblUser] ([pkUserID], [Name], [Address], [Sex], [Working]) VALUES (@pkUserID, @Name, @Address, @Sex, @Working)" 
        SelectCommand="SELECT * FROM [tblUser]" 
        UpdateCommand="UPDATE [tblUser] SET [Name] = @Name, [Address] = @Address, [Sex] = @Sex, [Working] = @Working WHERE [pkUserID] = @pkUserID">
        <DeleteParameters>
            <asp:Parameter Name="pkUserID" Type="String" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="Sex" Type="Boolean" />
            <asp:Parameter Name="Working" Type="Boolean" />
            <asp:Parameter Name="pkUserID" Type="String" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="pkUserID" Type="String" />
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="Sex" Type="Boolean" />
            <asp:Parameter Name="Working" Type="Boolean" />
        </InsertParameters>
    </asp:SqlDataSource>
    <hr />
    <br />
    
    <asp:Menu ID="mnuTest" runat="server" BackColor="#FFFBD6" 
        DynamicHorizontalOffset="2" Font-Names="Verdana" Font-Size="0.8em" 
        ForeColor="#990000" StaticSubMenuIndent="10px" 
        onmenuitemclick="mnuTest_MenuItemClick">
        <StaticSelectedStyle BackColor="#FFCC66" />
        <StaticMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
        <DynamicHoverStyle BackColor="#990000" ForeColor="White" />
        <DynamicMenuStyle BackColor="#FFFBD6" />
        <DynamicSelectedStyle BackColor="#FFCC66" />
        <DynamicMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
        <StaticHoverStyle BackColor="#990000" ForeColor="White" />
    </asp:Menu>
    
    <br />
    <asp:Label ID="lblMenuTest" runat="server"></asp:Label>
    
    </form>
</body>
</html>
